### PR TITLE
Use flexbox for input element instead of calculating width manually

### PR DESCRIPTION
**Pull request by juhana**
plus some other modern CSS features

### CODE REVIEW

**Comment by curiousdannii** [comment]
This should probably be made at https://github.com/erkyrath/glkote/

Does this fix the bug of #32?

**Comment by juhana** [comment]
Oops, didn't notice that Glkote has a separate repo. (It could be added as a subrepository here to avoid the need for syncing it manually.)

I don't think this fixes the Android bug, I assume the problem is removing and re-adding the input field? I can try it though. This is in response to https://intfiction.org/t/quixe-chrome-cursor-position/42413

**Comment by juhana** [comment]
There doesn't seem to be any difference in Android, although it's not as bad as #32 describes: City of Secrets doesn't get stuck anymore but the keyboard bounces up and down between turns.

**Comment by erkyrath** [comment]
Closing this, as it doesn't seem to do what we need and the Chrome bug has been fixed already. See comments at https://github.com/erkyrath/glkote/pull/36 .

**Pull request closed without merging**
