### PR TITLE
Super big speedup for pop_callstub

### PR DESCRIPTION
**Pull request by eevee**
Spent a few hours looking, and this was the only major improvement I found.

7% improvement on Firefox, 16% improvement on Chromium.  (Measuring Counterfeit Monkey's startup time, as usual.)

### CODE REVIEW

**Comment by erkyrath** [comment]
Okay, you win, there was easy fodder left. I owe you a drink and/or pastry. :)

**Comment by erkyrath** [comment]
Um, hm. I have tested this under current Safari, Firefox, and Chrome (not Chromium) and there is no clear difference. Your change might be 1% to 2% slower.

**Comment by erkyrath** [comment]
Ok, on Lectrote's Chromium I see the difference.

I think Chrome just updated, let me try it again...

**Comment by erkyrath** [comment]
Yup. No improvement in Chrome 44, which is what I had before. But in 47 (the Lectrote package) or 48 (the latest Mac desktop package) it is visible. I'm getting more like 10% than 16%, but hey -- good enough.

**Comment by erkyrath** [comment]
Credit as "Eevee" or what name?

**Comment by eevee** [comment]
I'm mostly known as Eevee, yeah  :)

**Pull request merged**
